import os

TELEGRAM_TOKEN = os.environ.get('TELEGRAM_TOKEN', '7704131958:AAFi27elWlhxIABzV6rJX2ow_QQOjW6r88Q')
CHAT_ID = os.environ.get('CHAT_ID', '497241426')
SYMBOLS = [
    'BTC/USDT',
    'DOGE/USDT', 'SHIB/USDT', 'PEPE/USDT', 'FLOKI/USDT', 'BONK/USDT',
    'ETH/USDT', 'BNB/USDT', 'SOL/USDT', 'XRP/USDT', 'ADA/USDT'
]
TIMEFRAME = '1h'
