import os

TELEGRAM_TOKEN = os.environ.get('TELEGRAM_TOKEN', 'YOUR_DEFAULT_TOKEN')
CHAT_ID = os.environ.get('CHAT_ID', 'YOUR_DEFAULT_CHAT_ID')
SYMBOLS = [
    'BTC/USDT',
    'DOGE/USDT', 'SHIB/USDT', 'PEPE/USDT', 'FLOKI/USDT', 'BONK/USDT',
    'ETH/USDT', 'BNB/USDT', 'SOL/USDT', 'XRP/USDT', 'ADA/USDT'
]
TIMEFRAME = '1h'
